AnyOrder/Models/AddOn.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AnyOrder.Models
{
    public class AddOn
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public float Cost { get; set; }
    }
}

AnyOrder/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AnyOrder.Models
{
    public class Customer
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

AnyOrder/Models/MenuItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AnyOrder.Models
{
    public class MenuItem
    {
        public int Id { get; set; }
        public string Summary { get; set; }
        public float Price { get; set; }
        public string ItemType { get; set; }
    }
}

AnyOrder/Models/Order.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Vidly.Models
{
    public class Order
    {
        public int Id { get; set; }
        public string Summary { get; set; }
        public float Cost { get; set; }
    }
}

AnyOrder/ViewModels/CustomerDetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using AnyOrder.Models;

namespace AnyOrder.ViewModels
{
    public class CustomerDetailsViewModel
    {
        public Customer Customer { get; set; }
    }
}

AnyOrder/ViewModels/CustomersViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using AnyOrder.Models;

namespace AnyOrder.ViewModels
{
    public class CustomersViewModel
    {
        public List<Customer> Customers { get; set; }
    }
}

AnyOrder/ViewModels/NewOrderViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using AnyOrder.Models;

namespace AnyOrder.ViewModels
{
    public class NewOrderViewModel
    {
        public List<MenuItem> Meals { get; set; }
        public List<AddOn> AddOns { get; set; }
    }
}

AnyOrder/ViewModels/OrdersViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using AnyOrder.Models;

namespace AnyOrder.ViewModels
{
    public class OrdersViewModel
    {
        public List<MenuItem> Orders { get; set; }
    }
}

AnyOrder/ViewModels/RandomMovieViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Vidly.Models;

namespace Vidly.ViewModels
{
    public class RandomOrderViewModel
    {
        public Order Order { get; set; }
        public List<Customer> Customers { get; set; }
    }
}

AnyOrder/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AnyOrder.Models;
using AnyOrder.ViewModels;

namespace AnyOrder.Controllers
{
    public class CustomersController : Controller
    {
        // GET: Customers
        [Route("customers")]
        [Route("customers/customers")]
        public ActionResult Customers()
        {
            var customers = GetCustomers();

            var viewModel = new CustomersViewModel { Customers = customers.ToList() };

            return View(viewModel);
        }

        [Route("customers/details/{id}")]
        public ActionResult Details(int id)
        {
            var customer = GetCustomers().SingleOrDefault(c => c.Id == id);

            if (customer == null)
                return HttpNotFound();

            return View(customer);
        }

        private IEnumerable<Customer> GetCustomers()
        {
            return new List<Customer>
            {
                new Customer { Id = 1, Name = "John Smith" },
                new Customer { Id = 2, Name = "Mary Williams" }
            };
        }
    }
}

AnyOrder/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AnyOrder.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

AnyOrder/Controllers/MenuController.cs
using AnyOrder.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Mvc;

namespace Vidly.Controllers
{
    public class MenuController : ApiController
    {
        [System.Web.Mvc.Route("menu")]
        [System.Web.Mvc.Route("menu/menu")]
        public IEnumerable<MenuItem> Menu()
        {
            var menu = GetMenu();

            return menu;
        }

        public MenuItem MenuItemDetails(int id)
        {
            MenuItem menuItem = GetMenu().SingleOrDefault(m => m.Id == id);

            if (menuItem == null) 
                throw new HttpResponseException(HttpStatusCode.NotFound);
            else
                return menuItem;
        }

        private IEnumerable<MenuItem> GetMenu()
        {
            return new List<MenuItem>
            {

            };
        } 
    }
}

AnyOrder/Controllers/NewOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AnyOrder.Models;
using AnyOrder.ViewModels;

namespace AnyOrder.Controllers
{
    public class NewOrderController : Controller
    {
        [Route("newrder")]
        [Route("neworder/neworder")]
        public ActionResult NewOrder()
        {
            var orders = new List<MenuItem>
            {
                new MenuItem { Summary = "Burger" },
                new MenuItem { Summary = "Pork" }
            };

            var viewModel = new OrdersViewModel { Orders = orders };

            return View(viewModel);
        }
    }
}

AnyOrder/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vidly.Models;
using Vidly.ViewModels;

namespace Vidly.Controllers
{
    public class OrdersController : Controller
    {
        // GET: Movies/Random
        public ActionResult Random()
        {
            var order = new Order() { Summary = "Steak" };
            var customers = new List<Customer>
            {
                new Customer {Name = "Customer 1"},
                new Customer {Name = "Customer 2"},
            };

            var viewModel = new RandomOrderViewModel
            {
                Order = order,
                Customers = customers
            };

            return View(viewModel);
        }

        [Route("orders")]
        [Route("orders/orders")]
        public ActionResult Orders()
        {
            var orders = new List<Order>
            {
                new Order { Summary = "Burger" },
                new Order { Summary = "Pork" }
            };

            var viewModel = new OrdersViewModel { Orders = orders };

            return View(viewModel);
        }
    }
}

AnyOrder/Views/Customers/Customers.cshtml
@model AnyOrder.ViewModels.CustomersViewModel  
@{ 
    ViewBag.Title = "Customers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Customers</h2>
@if (Model.Customers.Count == 0)
            {
                <p>No customers have signed up.</p>
            }
else { 
<table class="table table-bordered table-hover">
    <tr>
        <th>Customers</th>
    </tr>
    @foreach (var customer in Model.Customers)
    {
        <tr>
            <td>@Html.ActionLink(customer.Name, "Details", "Customers", new { id = customer.Id }, null)</td>
        </tr>
    }
</table>
}

AnyOrder/Views/Customers/Details.cshtml
@model AnyOrder.Models.Customer
@{
    ViewBag.Title = Model.Name;
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>@Model.Name</h2>

AnyOrder/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AnyOrder/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AnyOrder/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

AnyOrder/Views/Orders/Orders.cshtml
@model AnyOrder.ViewModels.OrdersViewModel
@{ 
    ViewBag.Title = "Orders";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Orders</h2>
@if (Model.Orders.Count == 0)
            {
                <p>No orders are made.</p>
            }

<table class="table table-bordered table-hover">
    <tr>
        <th>Orders</th>
    </tr>
    @foreach (var order in Model.Orders)
    {
        <tr>
            <td>@order.Summary</td>
            <td>@order.Price</td>
        </tr>
    }
</table>

AnyOrder/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Html.Partial("_NavBar")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

AnyOrder/Views/Shared/_NavBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("AnyOrder", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Customers", "Customers", "Customers")</li>
                <li>@Html.ActionLink("Orders", "Orders", "Orders")</li>
                <li>@Html.ActionLink("New Order", "NewOrder", "NewOrder")</li>
            </ul>
        </div>
    </div>
</div>